### ISSUE TITLE
Nx vs NaXX - explanation wanted

### ISSUE THREAD

**Issue by pmoule** [inexorabletash/travellermap#246]
This is more a wanted explanation, rather than an issue.
In some sectors (mostly in folder `res\Sectors\Distant Fringe`) allegiance code `Nx` is used.

Example:
https://github.com/inexorabletash/travellermap/blob/main/res/Sectors/Distant%20Fringe/Abyss.txt
```
Hex  Name                 UWP       Remarks              {Ix} (Ex) [Cx] N B Z PBG W  A  Stellar     
---- -------------------- --------- -------------------- ---- ---- ---- - - - --- -- -- ------------
0102 Jorutha              ?311???-? Ic Tz                               - - - ?11 8  Nx M4 V        
0901 Masikaro             ?6A4???-? Fl Tz                               - - - ?22 10 Nx M3 V M7 V   
1103 Gerund               ?512???-? Ic Tz                               - - - ?30 7  Nx M6 V        
1706 Erim Arut            ?650???-? De He Po                            - - - ?30 11 Nx M7 III M2 V 
2803 Boroyen              ?421???-? He Po Sa                            - - - ?01 6  Nx M8 V        
2903 Darga                ?000???-? As Va                               - - - ?11 7  Nx M7 V M8 V    
1211 Farisil              ?686???-? Ga Tz                               - - - ?10 7  Nx K1 V        
1129 Allathur             ?6A3???-? Fl Tz                               - - - ?21 5  Nx M0 V        
2336 Hamarah              ?432???-? Po Tz                               - - - ?10 8  Nx M2 V 
```
In related [xml](https://github.com/inexorabletash/travellermap/blob/main/res/Sectors/Distant%20Fringe/Abyss.xml#L10) `Nx` is described as 
`<Allegiance Code="Nx">Non-aligned, unclaimed</Allegiance>`

In [allegiance_codes.tab](https://github.com/inexorabletash/travellermap/blob/main/res/t5ss/allegiance_codes.tab#L127) `NaXX` is described as follows: 
`NaXX	Na	Na	Non-Aligned, unclaimed	various`

Ignoring the spelling, there seems to be an identical intention for used codes.

First of all, there is no problem with this at all. Sector data are coherent in themselves, surveys contain all required information and systems' allegiances are perfectly displayed in _Traveller Map_. No real worries.

When it would come to having kind of consistency across sectors for a single milieu or even the full universe and migrating contents to _T5SS_, wouldn't it make sense to replace e.g. `Nx` by `NaXX`? `Nx` is just one example for many allegiance codes. Of course, this might be Sisyphean work, because sector authors may freely invent own codes within sector scope. 

So, out of curiosity and because sorting allegiance codes is currentIy some fun for me :slightly_smiling_face: ... are there ideas or intentions to somehow control the possible 'flooding' of allegiance codes before they appear in _Traveller Map_?

**Comment by inexorabletash** [comment]
Excellent question. First, some background:

To clarify, T5SS is the T5 Sector Survey, intended to produce an official dataset. It's an ongoing process. As part of handling T5 data, I defined two new file formats - [tab-delimited](https://travellermap.com/doc/fileformats#t5-tab-delimited-format) (easily machine parsable, good for spreadsheets, bad for humans) and [column-delimited](https://travellermap.com/doc/fileformats#t5-column-delimited-format) (human readable but harder to parse). The T5SS also defined a curated set of 4-character allegiance codes.  

The T5SS dataset should be fully consistent, and the sectors are described using one of the T5 formats. Up until recently, the canonical dataset was actually in a spreadsheet, but it's now the .TAB files in the repo, for sectors tagged "Official" or "InReview". In theory, only T5SS-defined sophont codes and allegiance codes should be used, but there may be bugs.

For unofficial data, sectors can be defined using one of the T5 formats or the legacy formats. Obviously a lot of older data is present in what I call "legacy" or "SEC" format. That only supports 2-character allegiance codes. Unofficial data can also be in the T5 formats, and use 4-character codes. The 2-character codes can be anything, and although there is a core set that was widely used in publications back through the 1980s, many are re-used with different meanings across legacy data.

Since we want the 4-character codes to be carefully considered, individual sector authors can't just make them up. I require (unless I've made a mistake!) that they stick to 2-character codes and define them in the metadata for the sector.

Okay, that's a lot of background. To your specific question:

* _"Would it make sense to replace `Nx` by `NaXX`?"_

Probably - if the sector is upgraded from a SEC format to a T5 format. This is generally lossless but it's effort and could introduce problems, e.g. changing base codes from single-character (like A or B) to T5 multi-character (e.g. NS, NW). Unlike allegiances where there was some standardization in how they were documented so I could extract metadata, the base code situation was a lot messier. Also, general laziness - if the SEC file has a bunch of Nx it's easier to just slap the metadata definition.

Bulk-upgrading is therefore not something I'm spending my time on.

* _"are there ideas or intentions to somehow control the possible 'flooding' of allegiance codes before they appear in Traveller Map?"_

The incoming rate of sectors is pretty low, and generally falls into one of 3 categories:
* Non-OTU sectors, which I call "Faraway" because I tend to drop them on the map far away from charted space. You can think of these as alternate universes, but without crazy UI to deal with that. Since this generally doesn't use OTU codes, sectors are going to have to define their own allegiances.
* OTU-adjacent sectors. These are things which are unofficial fan additions usually scattered around the periphery of Charted Space.  There's a limited amount of this, and since it's outside the main borders of official space it needs to define custom allegiances as well.
* OTU Charted Space iterations - we now have at least preliminary data for all of Charted Space (the quadrangle bounded by Zho, K'kree, Hiver, and Aslan space). Some of this is very old/sketchy/raw, some of it is the officially blessed T5SS data. At this point data usually migrates from raw to T5SS "InReview" to T5SS "Official" when someone (e.g. Mongoose) is going to publish a book and we pile on to clean up the data before it makes it into print. This is where we realize that e.g. we should recode a sector from using KC to CsTw, or when we need to introduce a new code entirely - and then argue about what the official polity name is. Then add it to the `res/t5ss/allegiance_codes.tab` file. 

So... there's not really a worry about "flooding", since Charted Space/OTU is finite, and that's the only place we need to worry about a central registry.

That's a long answer - I'm glad you asked and are paying attention to details!!!

Now... what's obviously a problem is that as a single curator of all of this I'm not perfect at auditing additions, and the tooling could be improved. There are several errors that aren't called out via tools/lintsec that really need to be surfaced; right now they only appear when running an admin tool. And I don't always run that - oops.

**Comment by pmoule** [comment]
Many thanks for your detailed explanation. Really appreciate that!
I was not aware about the fact, that authors should stick to 2-char codes. Also insights about "Faraway" sectors make things much more comprehensive. So I should have read https://travellermap.com/doc/submit beforehand :) 

As there's no "flooding" to be assumed,... no problem apart from the one you mentioned in being a single curator. 
Yeah, hmm. Start with starting a friendship with _crontab_  about running the admin tool :wink:

So to reduce the pile of work, this issue can be closed :smile:

Looking forward to meeting you in other comments.
